# Generated by Django 5.0.4 on 2024-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleappmodel',
            name='itemvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sampleappmodel',
            name='itemname',
            field=models.CharField(max_length=100),
        ),
    ]
